# Generated by Django 6.0.2 on 2026-04-03 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectmodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/images/', verbose_name='Imagen')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición (0 = principal)', verbose_name='Orden')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.projectmodel', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Imagen del proyecto',
                'verbose_name_plural': 'Imágenes del proyecto',
            },
        ),
    ]
