# Generated by Django 6.0.5 on 2026-07-18 05:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_projectimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
