# Generated by Django 6.0.5 on 2026-07-18 05:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_contact_options_alter_contact_comentario_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
